/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : ContactMessageId,
  'name' : string,
  'isOpen' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type ContactMessageId = bigint;
export interface Employee {
  'id' : EmployeeId,
  'salary' : Salary,
  'leaveBalance' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'joiningDate' : bigint,
  'isOpen' : boolean,
  'pfDetails' : string,
  'totalLeavesTaken' : bigint,
  'bonus' : bigint,
}
export type EmployeeId = bigint;
export interface JobRole {
  'id' : JobRoleId,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'isOpen' : boolean,
  'linkedInUrl' : string,
  'location' : Location,
}
export type JobRoleId = bigint;
export interface LeaveEntry {
  'id' : LeaveId,
  'status' : string,
  'endDate' : bigint,
  'createdAt' : bigint,
  'isOpen' : boolean,
  'employeeId' : EmployeeId,
  'leaveType' : string,
  'startDate' : bigint,
  'reason' : string,
}
export type LeaveId = bigint;
export interface Location { 'country' : string, 'city' : string }
export interface OfficeAddress {
  'title' : string,
  'email' : string,
  'addressLines' : Array<string>,
  'phone' : string,
}
export interface Payslip {
  'id' : PayslipId,
  'month' : bigint,
  'leaveBalance' : bigint,
  'createdAt' : bigint,
  'year' : bigint,
  'employeeId' : EmployeeId,
  'salaryDetails' : Salary,
}
export type PayslipId = bigint;
export interface QuickLeaveMarkRequest {
  'employeeId' : EmployeeId,
  'leaveDate' : bigint,
  'leaveType' : string,
  'reason' : string,
}
export interface Salary {
  'base' : bigint,
  'finalPayable' : bigint,
  'bonus' : bigint,
  'pfDeduction' : bigint,
}
export interface Task {
  'id' : TaskId,
  'title' : string,
  'assignedTo' : Array<EmployeeId>,
  'createdAt' : bigint,
  'dueDate' : bigint,
  'description' : string,
  'priority' : TaskPriority,
  'isComplete' : boolean,
}
export type TaskId = bigint;
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface TaskUpdate {
  'title' : string,
  'assignedTo' : Array<EmployeeId>,
  'dueDate' : bigint,
  'description' : string,
  'priority' : TaskPriority,
  'isComplete' : boolean,
}
export interface UserInfo {
  'principal' : Principal,
  'role' : UserRole,
  'profile' : [] | [UserProfile],
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLeaveEntry' : ActorMethod<[EmployeeId, bigint, bigint, string], LeaveId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'associateEmployeeWithPrincipal' : ActorMethod<[EmployeeId], undefined>,
  'createEmployee' : ActorMethod<
    [string, bigint, bigint, string, bigint],
    EmployeeId
  >,
  'createJobRole' : ActorMethod<[JobRole], JobRoleId>,
  'createTask' : ActorMethod<
    [string, string, bigint, TaskPriority, Array<EmployeeId>],
    TaskId
  >,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'generateMonthlyPayslips' : ActorMethod<[bigint, bigint], undefined>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllEmployeesSorted' : ActorMethod<[], Array<Employee>>,
  'getAllOpenJobRoles' : ActorMethod<[], Array<JobRole>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAssociatedEmployeeId' : ActorMethod<[Principal], [] | [EmployeeId]>,
  'getCallerRole' : ActorMethod<[], UserRole>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessage' : ActorMethod<[ContactMessageId], [] | [ContactMessage]>,
  'getEmployee' : ActorMethod<[EmployeeId], [] | [Employee]>,
  'getEmployeeLeaveBalance' : ActorMethod<[EmployeeId], bigint>,
  'getEmployeeLeaveEntries' : ActorMethod<[EmployeeId], Array<LeaveEntry>>,
  'getEmployeePayslips' : ActorMethod<[EmployeeId], Array<Payslip>>,
  'getEmployeeTasks' : ActorMethod<[EmployeeId], Array<Task>>,
  'getOfficeAddress' : ActorMethod<[], OfficeAddress>,
  'getOpenJobRolesCount' : ActorMethod<[], bigint>,
  'getPayslip' : ActorMethod<[PayslipId], [] | [Payslip]>,
  'getTask' : ActorMethod<[TaskId], [] | [Task]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], UserRole>,
  'hasPendingTasks' : ActorMethod<[EmployeeId], boolean>,
  'hasPermission' : ActorMethod<[Principal, UserRole], boolean>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserInfo>>,
  'quickLeaveMark' : ActorMethod<[QuickLeaveMarkRequest], LeaveId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string],
    ContactMessageId
  >,
  'updateEmployeeSalary' : ActorMethod<[EmployeeId, bigint], undefined>,
  'updateTask' : ActorMethod<[TaskId, TaskUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];