/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : ContactMessageId,
  'name' : string,
  'isOpen' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type ContactMessageId = bigint;
export interface Employee {
  'id' : EmployeeId,
  'salary' : Salary,
  'leaveBalance' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'joiningDate' : bigint,
  'isOpen' : boolean,
  'pfDetails' : string,
  'totalLeavesTaken' : bigint,
  'bonus' : bigint,
}
export type EmployeeId = bigint;
export interface JobRole {
  'id' : JobRoleId,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'isOpen' : boolean,
  'linkedInUrl' : string,
  'location' : Location,
}
export type JobRoleId = bigint;
export interface LeaveEntry {
  'id' : LeaveId,
  'status' : string,
  'endDate' : bigint,
  'createdAt' : bigint,
  'isOpen' : boolean,
  'employeeId' : EmployeeId,
  'startDate' : bigint,
  'reason' : string,
}
export type LeaveId = bigint;
export interface Location { 'country' : string, 'city' : string }
export interface Salary {
  'base' : bigint,
  'finalPayable' : bigint,
  'bonus' : bigint,
  'pfDeduction' : bigint,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLeaveEntry' : ActorMethod<[EmployeeId, bigint, bigint, string], LeaveId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEmployee' : ActorMethod<
    [string, bigint, bigint, string, bigint],
    EmployeeId
  >,
  'createJobRole' : ActorMethod<[JobRole], JobRoleId>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllEmployeesSorted' : ActorMethod<[], Array<Employee>>,
  'getAllOpenJobRoles' : ActorMethod<[], Array<JobRole>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessage' : ActorMethod<[ContactMessageId], [] | [ContactMessage]>,
  'getEmployee' : ActorMethod<[EmployeeId], [] | [Employee]>,
  'getEmployeeLeaveBalance' : ActorMethod<[EmployeeId], bigint>,
  'getEmployeeLeaveEntries' : ActorMethod<[EmployeeId], Array<LeaveEntry>>,
  'getOpenJobRolesCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasPermission' : ActorMethod<[Principal, UserRole], boolean>,
  'initializeSystem' : ActorMethod<[string, string], undefined>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string],
    ContactMessageId
  >,
  'updateEmployeeSalary' : ActorMethod<[EmployeeId, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];