/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmployeeId = IDL.Nat;
export const LeaveId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobRoleId = IDL.Nat;
export const Location = IDL.Record({ 'country' : IDL.Text, 'city' : IDL.Text });
export const JobRole = IDL.Record({
  'id' : JobRoleId,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isOpen' : IDL.Bool,
  'linkedInUrl' : IDL.Text,
  'location' : Location,
});
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const TaskId = IDL.Nat;
export const ContactMessageId = IDL.Nat;
export const ContactMessage = IDL.Record({
  'id' : ContactMessageId,
  'name' : IDL.Text,
  'isOpen' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Salary = IDL.Record({
  'base' : IDL.Nat,
  'finalPayable' : IDL.Nat,
  'bonus' : IDL.Nat,
  'pfDeduction' : IDL.Nat,
});
export const Employee = IDL.Record({
  'id' : EmployeeId,
  'salary' : Salary,
  'leaveBalance' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'joiningDate' : IDL.Int,
  'isOpen' : IDL.Bool,
  'pfDetails' : IDL.Text,
  'totalLeavesTaken' : IDL.Nat,
  'bonus' : IDL.Nat,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'assignedTo' : IDL.Vec(EmployeeId),
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'priority' : TaskPriority,
  'isComplete' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const LeaveEntry = IDL.Record({
  'id' : LeaveId,
  'status' : IDL.Text,
  'endDate' : IDL.Int,
  'createdAt' : IDL.Int,
  'isOpen' : IDL.Bool,
  'employeeId' : EmployeeId,
  'leaveType' : IDL.Text,
  'startDate' : IDL.Int,
  'reason' : IDL.Text,
});
export const PayslipId = IDL.Nat;
export const Payslip = IDL.Record({
  'id' : PayslipId,
  'month' : IDL.Nat,
  'leaveBalance' : IDL.Nat,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'employeeId' : EmployeeId,
  'salaryDetails' : Salary,
});
export const OfficeAddress = IDL.Record({
  'title' : IDL.Text,
  'email' : IDL.Text,
  'addressLines' : IDL.Vec(IDL.Text),
  'phone' : IDL.Text,
});
export const UserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'profile' : IDL.Opt(UserProfile),
});
export const QuickLeaveMarkRequest = IDL.Record({
  'employeeId' : EmployeeId,
  'leaveDate' : IDL.Int,
  'leaveType' : IDL.Text,
  'reason' : IDL.Text,
});
export const TaskUpdate = IDL.Record({
  'title' : IDL.Text,
  'assignedTo' : IDL.Vec(EmployeeId),
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'priority' : TaskPriority,
  'isComplete' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLeaveEntry' : IDL.Func(
      [EmployeeId, IDL.Int, IDL.Int, IDL.Text],
      [LeaveId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'associateEmployeeWithPrincipal' : IDL.Func([EmployeeId], [], []),
  'createEmployee' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Nat, IDL.Text, IDL.Nat],
      [EmployeeId],
      [],
    ),
  'createJobRole' : IDL.Func([JobRole], [JobRoleId], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, TaskPriority, IDL.Vec(EmployeeId)],
      [TaskId],
      [],
    ),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'generateMonthlyPayslips' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllEmployeesSorted' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllOpenJobRoles' : IDL.Func([], [IDL.Vec(JobRole)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAssociatedEmployeeId' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(EmployeeId)],
      ['query'],
    ),
  'getCallerRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessage' : IDL.Func(
      [ContactMessageId],
      [IDL.Opt(ContactMessage)],
      ['query'],
    ),
  'getEmployee' : IDL.Func([EmployeeId], [IDL.Opt(Employee)], ['query']),
  'getEmployeeLeaveBalance' : IDL.Func([EmployeeId], [IDL.Nat], ['query']),
  'getEmployeeLeaveEntries' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(LeaveEntry)],
      ['query'],
    ),
  'getEmployeePayslips' : IDL.Func([EmployeeId], [IDL.Vec(Payslip)], ['query']),
  'getEmployeeTasks' : IDL.Func([EmployeeId], [IDL.Vec(Task)], ['query']),
  'getOfficeAddress' : IDL.Func([], [OfficeAddress], ['query']),
  'getOpenJobRolesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPayslip' : IDL.Func([PayslipId], [IDL.Opt(Payslip)], ['query']),
  'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'hasPendingTasks' : IDL.Func([EmployeeId], [IDL.Bool], ['query']),
  'hasPermission' : IDL.Func([IDL.Principal, UserRole], [IDL.Bool], ['query']),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'quickLeaveMark' : IDL.Func([QuickLeaveMarkRequest], [LeaveId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ContactMessageId],
      [],
    ),
  'updateEmployeeSalary' : IDL.Func([EmployeeId, IDL.Nat], [], []),
  'updateTask' : IDL.Func([TaskId, TaskUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmployeeId = IDL.Nat;
  const LeaveId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobRoleId = IDL.Nat;
  const Location = IDL.Record({ 'country' : IDL.Text, 'city' : IDL.Text });
  const JobRole = IDL.Record({
    'id' : JobRoleId,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isOpen' : IDL.Bool,
    'linkedInUrl' : IDL.Text,
    'location' : Location,
  });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TaskId = IDL.Nat;
  const ContactMessageId = IDL.Nat;
  const ContactMessage = IDL.Record({
    'id' : ContactMessageId,
    'name' : IDL.Text,
    'isOpen' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Salary = IDL.Record({
    'base' : IDL.Nat,
    'finalPayable' : IDL.Nat,
    'bonus' : IDL.Nat,
    'pfDeduction' : IDL.Nat,
  });
  const Employee = IDL.Record({
    'id' : EmployeeId,
    'salary' : Salary,
    'leaveBalance' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'joiningDate' : IDL.Int,
    'isOpen' : IDL.Bool,
    'pfDetails' : IDL.Text,
    'totalLeavesTaken' : IDL.Nat,
    'bonus' : IDL.Nat,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'assignedTo' : IDL.Vec(EmployeeId),
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'priority' : TaskPriority,
    'isComplete' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const LeaveEntry = IDL.Record({
    'id' : LeaveId,
    'status' : IDL.Text,
    'endDate' : IDL.Int,
    'createdAt' : IDL.Int,
    'isOpen' : IDL.Bool,
    'employeeId' : EmployeeId,
    'leaveType' : IDL.Text,
    'startDate' : IDL.Int,
    'reason' : IDL.Text,
  });
  const PayslipId = IDL.Nat;
  const Payslip = IDL.Record({
    'id' : PayslipId,
    'month' : IDL.Nat,
    'leaveBalance' : IDL.Nat,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'employeeId' : EmployeeId,
    'salaryDetails' : Salary,
  });
  const OfficeAddress = IDL.Record({
    'title' : IDL.Text,
    'email' : IDL.Text,
    'addressLines' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
  });
  const UserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'profile' : IDL.Opt(UserProfile),
  });
  const QuickLeaveMarkRequest = IDL.Record({
    'employeeId' : EmployeeId,
    'leaveDate' : IDL.Int,
    'leaveType' : IDL.Text,
    'reason' : IDL.Text,
  });
  const TaskUpdate = IDL.Record({
    'title' : IDL.Text,
    'assignedTo' : IDL.Vec(EmployeeId),
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'priority' : TaskPriority,
    'isComplete' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLeaveEntry' : IDL.Func(
        [EmployeeId, IDL.Int, IDL.Int, IDL.Text],
        [LeaveId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'associateEmployeeWithPrincipal' : IDL.Func([EmployeeId], [], []),
    'createEmployee' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Nat, IDL.Text, IDL.Nat],
        [EmployeeId],
        [],
      ),
    'createJobRole' : IDL.Func([JobRole], [JobRoleId], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, TaskPriority, IDL.Vec(EmployeeId)],
        [TaskId],
        [],
      ),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'generateMonthlyPayslips' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllEmployeesSorted' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllOpenJobRoles' : IDL.Func([], [IDL.Vec(JobRole)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAssociatedEmployeeId' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(EmployeeId)],
        ['query'],
      ),
    'getCallerRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessage' : IDL.Func(
        [ContactMessageId],
        [IDL.Opt(ContactMessage)],
        ['query'],
      ),
    'getEmployee' : IDL.Func([EmployeeId], [IDL.Opt(Employee)], ['query']),
    'getEmployeeLeaveBalance' : IDL.Func([EmployeeId], [IDL.Nat], ['query']),
    'getEmployeeLeaveEntries' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(LeaveEntry)],
        ['query'],
      ),
    'getEmployeePayslips' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(Payslip)],
        ['query'],
      ),
    'getEmployeeTasks' : IDL.Func([EmployeeId], [IDL.Vec(Task)], ['query']),
    'getOfficeAddress' : IDL.Func([], [OfficeAddress], ['query']),
    'getOpenJobRolesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPayslip' : IDL.Func([PayslipId], [IDL.Opt(Payslip)], ['query']),
    'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'hasPendingTasks' : IDL.Func([EmployeeId], [IDL.Bool], ['query']),
    'hasPermission' : IDL.Func(
        [IDL.Principal, UserRole],
        [IDL.Bool],
        ['query'],
      ),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'quickLeaveMark' : IDL.Func([QuickLeaveMarkRequest], [LeaveId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ContactMessageId],
        [],
      ),
    'updateEmployeeSalary' : IDL.Func([EmployeeId, IDL.Nat], [], []),
    'updateTask' : IDL.Func([TaskId, TaskUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };