/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    country: string;
    city: string;
}
export interface Salary {
    base: bigint;
    finalPayable: bigint;
    bonus: bigint;
    pfDeduction: bigint;
}
export type ContactMessageId = bigint;
export interface QuickLeaveMarkRequest {
    employeeId: EmployeeId;
    leaveDate: bigint;
    leaveType: string;
    reason: string;
}
export interface Task {
    id: TaskId;
    title: string;
    assignedTo: Array<EmployeeId>;
    createdAt: bigint;
    dueDate: bigint;
    description: string;
    priority: TaskPriority;
    isComplete: boolean;
}
export interface UserInfo {
    principal: Principal;
    role: UserRole;
    profile?: UserProfile;
}
export interface LeaveEntry {
    id: LeaveId;
    status: string;
    endDate: bigint;
    createdAt: bigint;
    isOpen: boolean;
    employeeId: EmployeeId;
    leaveType: string;
    startDate: bigint;
    reason: string;
}
export interface TaskUpdate {
    title: string;
    assignedTo: Array<EmployeeId>;
    dueDate: bigint;
    description: string;
    priority: TaskPriority;
    isComplete: boolean;
}
export type JobRoleId = bigint;
export interface LeaveSummary {
    leaveBalance: bigint;
    totalLeavesTaken: bigint;
}
export interface JobRole {
    id: JobRoleId;
    title: string;
    createdAt: bigint;
    description: string;
    isOpen: boolean;
    linkedInUrl: string;
    location: Location;
}
export interface OfficeAddress {
    title: string;
    email: string;
    addressLines: Array<string>;
    phone: string;
}
export type EmployeeId = bigint;
export type TaskId = bigint;
export interface Employee {
    id: EmployeeId;
    salary: Salary;
    leaveBalance: bigint;
    name: string;
    createdAt: bigint;
    joiningDate: bigint;
    isOpen: boolean;
    pfDetails: string;
    totalLeavesTaken: bigint;
    bonus: bigint;
}
export type PayslipId = bigint;
export type LeaveId = bigint;
export interface UserProfile {
    name: string;
    email: string;
}
export interface Payslip {
    id: PayslipId;
    month: bigint;
    leaveBalance: bigint;
    createdAt: bigint;
    year: bigint;
    employeeId: EmployeeId;
    salaryDetails: Salary;
}
export enum TaskPriority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLeaveEntry(employeeId: EmployeeId, startDate: bigint, endDate: bigint, reason: string): Promise<LeaveId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignUserRole(user: Principal, role: UserRole): Promise<void>;
    associateEmployeeWithPrincipal(employeeId: EmployeeId): Promise<void>;
    createEmployee(name: string, joiningDate: bigint, baseSalary: bigint, pfDetails: string, bonus: bigint): Promise<EmployeeId>;
    createJobRole(jobRoleEntry: JobRole): Promise<JobRoleId>;
    createTask(title: string, description: string, dueDate: bigint, priority: TaskPriority, assignedTo: Array<EmployeeId>): Promise<TaskId>;
    deleteTask(taskId: TaskId): Promise<void>;
    generateMonthlyPayslips(month: bigint, year: bigint): Promise<void>;
    getAllEmployeesPublic(): Promise<Array<Employee>>;
    getAllOpenJobRoles(): Promise<Array<JobRole>>;
    getAllTasksPublic(): Promise<Array<Task>>;
    getAssociatedEmployeeId(principal: Principal): Promise<EmployeeId | null>;
    getCallerAssociatedEmployeeId(): Promise<EmployeeId>;
    getCallerRole(): Promise<UserRole>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmployeeLeaveBalancePublic(employeeId: EmployeeId): Promise<bigint | null>;
    getEmployeeLeaveEntriesPublic(employeeId: EmployeeId): Promise<Array<LeaveEntry>>;
    getEmployeePayslips(employeeId: EmployeeId): Promise<Array<Payslip>>;
    getEmployeePublic(employeeId: EmployeeId): Promise<Employee | null>;
    getMyEmployee(): Promise<Employee>;
    getMyLeaveEntriesAndSummary(): Promise<[Array<LeaveEntry>, LeaveSummary]>;
    getMyPayslips(): Promise<Array<Payslip>>;
    getMyTasks(): Promise<Array<Task>>;
    getOfficeAddress(): Promise<OfficeAddress>;
    getOpenJobRolesCount(): Promise<bigint>;
    getPayslip(payslipId: PayslipId): Promise<Payslip | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(user: Principal): Promise<UserRole>;
    hasPermission(user: Principal, requiredRole: UserRole): Promise<boolean>;
    isAdmin(user: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listAllUsers(): Promise<Array<UserInfo>>;
    quickLeaveMark(request: QuickLeaveMarkRequest): Promise<LeaveId>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitContactMessage(name: string, email: string, message: string): Promise<ContactMessageId>;
    submitMyTimeOffRequest(startDate: bigint, endDate: bigint, leaveType: string, reason: string): Promise<LeaveId>;
    updateEmployeeSalary(employeeId: EmployeeId, newBaseSalary: bigint): Promise<void>;
    updateTask(taskId: TaskId, update: TaskUpdate): Promise<void>;
}
import type { Employee as _Employee, EmployeeId as _EmployeeId, Payslip as _Payslip, Task as _Task, TaskId as _TaskId, TaskPriority as _TaskPriority, TaskUpdate as _TaskUpdate, UserInfo as _UserInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLeaveEntry(arg0: EmployeeId, arg1: bigint, arg2: bigint, arg3: string): Promise<LeaveId> {
        if (this.processError) {
            try {
                const result = await this.actor.addLeaveEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLeaveEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async associateEmployeeWithPrincipal(arg0: EmployeeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.associateEmployeeWithPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.associateEmployeeWithPrincipal(arg0);
            return result;
        }
    }
    async createEmployee(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: bigint): Promise<EmployeeId> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createJobRole(arg0: JobRole): Promise<JobRoleId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobRole(arg0);
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: bigint, arg3: TaskPriority, arg4: Array<EmployeeId>): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_TaskPriority_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_TaskPriority_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async generateMonthlyPayslips(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateMonthlyPayslips(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateMonthlyPayslips(arg0, arg1);
            return result;
        }
    }
    async getAllEmployeesPublic(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployeesPublic();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployeesPublic();
            return result;
        }
    }
    async getAllOpenJobRoles(): Promise<Array<JobRole>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOpenJobRoles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOpenJobRoles();
            return result;
        }
    }
    async getAllTasksPublic(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasksPublic();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasksPublic();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssociatedEmployeeId(arg0: Principal): Promise<EmployeeId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssociatedEmployeeId(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssociatedEmployeeId(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAssociatedEmployeeId(): Promise<EmployeeId> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAssociatedEmployeeId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAssociatedEmployeeId();
            return result;
        }
    }
    async getCallerRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeLeaveBalancePublic(arg0: EmployeeId): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeLeaveBalancePublic(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeLeaveBalancePublic(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeLeaveEntriesPublic(arg0: EmployeeId): Promise<Array<LeaveEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeLeaveEntriesPublic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeLeaveEntriesPublic(arg0);
            return result;
        }
    }
    async getEmployeePayslips(arg0: EmployeeId): Promise<Array<Payslip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeePayslips(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeePayslips(arg0);
            return result;
        }
    }
    async getEmployeePublic(arg0: EmployeeId): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeePublic(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeePublic(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEmployee(): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEmployee();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEmployee();
            return result;
        }
    }
    async getMyLeaveEntriesAndSummary(): Promise<[Array<LeaveEntry>, LeaveSummary]> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLeaveEntriesAndSummary();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLeaveEntriesAndSummary();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getMyPayslips(): Promise<Array<Payslip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPayslips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPayslips();
            return result;
        }
    }
    async getMyTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTasks();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTasks();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfficeAddress(): Promise<OfficeAddress> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficeAddress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficeAddress();
            return result;
        }
    }
    async getOpenJobRolesCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenJobRolesCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenJobRolesCount();
            return result;
        }
    }
    async getPayslip(arg0: PayslipId): Promise<Payslip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayslip(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayslip(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: Principal): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasPermission(arg0: Principal, arg1: UserRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasPermission(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasPermission(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async quickLeaveMark(arg0: QuickLeaveMarkRequest): Promise<LeaveId> {
        if (this.processError) {
            try {
                const result = await this.actor.quickLeaveMark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.quickLeaveMark(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitContactMessage(arg0: string, arg1: string, arg2: string): Promise<ContactMessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async submitMyTimeOffRequest(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<LeaveId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMyTimeOffRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMyTimeOffRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateEmployeeSalary(arg0: EmployeeId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployeeSalary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployeeSalary(arg0, arg1);
            return result;
        }
    }
    async updateTask(arg0: TaskId, arg1: TaskUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_TaskUpdate_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_TaskUpdate_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_TaskPriority_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserInfo_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserInfo): UserInfo {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployeeId]): EmployeeId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payslip]): Payslip | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
    profile: [] | [_UserProfile];
}): {
    principal: Principal;
    role: UserRole;
    profile?: UserProfile;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n11(_uploadFile, _downloadFile, value.role),
        profile: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    title: string;
    assignedTo: Array<_EmployeeId>;
    createdAt: bigint;
    dueDate: bigint;
    description: string;
    priority: _TaskPriority;
    isComplete: boolean;
}): {
    id: TaskId;
    title: string;
    assignedTo: Array<EmployeeId>;
    createdAt: bigint;
    dueDate: bigint;
    description: string;
    priority: TaskPriority;
    isComplete: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        assignedTo: value.assignedTo,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        description: value.description,
        priority: from_candid_TaskPriority_n8(_uploadFile, _downloadFile, value.priority),
        isComplete: value.isComplete
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): TaskPriority {
    return "low" in value ? TaskPriority.low : "high" in value ? TaskPriority.high : "medium" in value ? TaskPriority.medium : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserInfo>): Array<UserInfo> {
    return value.map((x)=>from_candid_UserInfo_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n6(_uploadFile, _downloadFile, x));
}
function to_candid_TaskPriority_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TaskUpdate_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskUpdate): _TaskUpdate {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    assignedTo: Array<EmployeeId>;
    dueDate: bigint;
    description: string;
    priority: TaskPriority;
    isComplete: boolean;
}): {
    title: string;
    assignedTo: Array<_EmployeeId>;
    dueDate: bigint;
    description: string;
    priority: _TaskPriority;
    isComplete: boolean;
} {
    return {
        title: value.title,
        assignedTo: value.assignedTo,
        dueDate: value.dueDate,
        description: value.description,
        priority: to_candid_TaskPriority_n3(_uploadFile, _downloadFile, value.priority),
        isComplete: value.isComplete
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == TaskPriority.low ? {
        low: null
    } : value == TaskPriority.high ? {
        high: null
    } : value == TaskPriority.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
